---
title: "Fuentes de datos"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

>La lista original es de Roger D. Peng, pero es una lista de 2014 por lo que algunos de los sitios originales han dejado de funcionar y se han suprimido. Además se han incorporado otros que me son más cercanos como los sitios de Gobierno Abierto de España, Cataluña, Hospitalet o Barcelona.

## Open Government Sites

* España [https://datos.gob.es/](https://datos.gob.es/)
* Catalunya [https://governobert.gencat.cat/ca/dades_obertes/](https://governobert.gencat.cat/ca/dades_obertes/)
* L'Hospitalet de Llobregat [https://opendata.l-h.cat/](https://opendata.l-h.cat/)
* Barcelona [https://opendata-ajuntament.barcelona.cat/es/](https://opendata-ajuntament.barcelona.cat/es/)
* Naciones Unidas [http://data.un.org/](http://data.un.org/)
* ESTADOS UNIDOS [http://www.data.gov/](http://www.data.gov/)
  * [Lista de ciudades/estados con datos abiertos](http://simplystatistics.org/2012/01/02/list-of-cities-states-with-open-data-help-me-find/)
* Reino Unido [http://data.gov.uk/](http://data.gov.uk/)
* Francia [http://www.data.gouv.fr/](http://www.data.gouv.fr/)
* Ghana [http://data.gov.gh/](http://data.gov.gh/)
* Australia [http://data.gov.au/](http://data.gov.au/)
* Alemania [https://www.govdata.de/](https://www.govdata.de/) 
* Hong Kong [http://www.gov.hk/en/theme/psi/datasets/](http://www.gov.hk/en/theme/psi/datasets/)
* Japón [http://www.data.go.jp/](https://www.data.go.jp/?lang=en)
* Muchos más [http://www.data.gov/opendatasites](http://www.data.gov/opendatasites)

## Gapminder

* [http://www.gapminder.org/](http://www.gapminder.org/)

## Survey data from the United States

* [http://www.asdfree.com/](http://www.asdfree.com/)

## Infochimps Marketplace

* [http://www.infochimps.com/marketplace](http://www.infochimps.com/marketplace)

## Kaggle

* [http://www.kaggle.com/](http://www.kaggle.com/)

## Colecciones de científicos de datos

* [Jeff Hammerbacher](http://www.quora.com/Jeff-Hammerbacher/Introduction-to-Data-Science-Data-Sets)
* [Gregory Piatetsky-Shapiro](http://www.kdnuggets.com/gps.html)

## Colecciones más especializadas

* [Stanford Large Network Data](http://snap.stanford.edu/data/)
* [UCI Machine Learning](http://archive.ics.uci.edu/ml/)
* [KDD Nugets Datasets](http://www.kdnuggets.com/datasets/index.html)
* [CMU Statlib](http://lib.stat.cmu.edu/datasets/)
* [Gene expression omnibus](http://www.ncbi.nlm.nih.gov/geo/)
* [ArXiv Data](http://arxiv.org/help/bulk_data)
* [Public Data Sets on Amazon Web Services](http://aws.amazon.com/publicdatasets/)

## Algunas API con interfaces de R

* Twitter
  * [la API de Twitter](https://dev.twitter.com/) 
  * [Paquete twitteR](http://cran.r-project.org/web/packages/twitteR/index.html)
  * [Paquete RTweet](https://cran.r-project.org/web/packages/rtweet/rtweet.pdf)
* [figshare](http://api.figshare.com/docs/intro.html) y [rfigshare](http://cran.r-project.org/web/packages/rfigshare/index.html)
* [PLoS](http://api.plos.org/) y [rplos](http://cran.r-project.org/web/packages/rplos/rplos.pdf)
* [rOpenSci](http://ropensci.org/packages/index.html)
* Facebook
  * [API Facebook](https://developers.facebook.com/)
  * [Paquete RFacebook](http://cran.r-project.org/web/packages/Rfacebook/)
* [Google maps](https://developers.google.com/maps/) y [RGoogleMaps](http://cran.r-project.org/web/packages/RgoogleMaps/index.html)